/* eslint-disable prettier/prettier */

// text used in project..
export default {
  email: 'Email',
  password: 'Password',
  newPassword: 'New Password',
  confirmPassword: 'Confirm Password',
  forgotPassword: 'Forgot Password?',
  name: 'Name',
  login: 'Login',
  signIn: 'Sign In',
  signOut: 'Sign out',
  signUp: 'Sign Up',
  findBestDeal: 'Find the best deals on flights to anywhere in the world!',
  dontHaveAccount: "Don't have an account?",
  alreadyHaveAccount: 'Already have an account?',
  signUpNow: 'Sign Up Now',
  signInNow: 'Sign In Now',
  activeOpacity: 0.75,
  flights: 'FLIGHT',
  hotels: 'HOTELS',
  cars: 'CARS',
  to: 'To',
  deppartureDate: 'Departure Date',
  deppartureTime: 'Departure Time',
  cabinClass: 'Cabin Class & Passengers',
  search: 'Search Flight',
  oneway: 'One way',
  roundTrip: 'Round trip',
  returnDate: 'Return Date',
  returnTime: 'Return Time',
  location: 'Location',
  checkIn: 'Check In',
  checkOut: 'Check Out',
  rooms: 'Rooms',
  pickup: 'Pickup',
  sameAsPickup: 'Same as Pickup',
  discountCode: 'Discount Code',
  discountType: 'Discount Type',
  discountCompany: 'Discount Company',
  welcomeTo: 'Welcome to',
  travelClub: 'travelclub',
  IQ: 'IQ',
  asGuest: 'Continue with as a guest',
  or: 'or',
  loginGoogle: 'Login with google',
  loginFacebook: 'Login with facebook',
  from: 'From',
  OTPverify: 'OTP Verification',
  weHaveSentOTP: 'We have sent you an verification code on your email',
  notReceiveOTP: "Don't receive the OTP?",
  resentOTP: 'Resend OTP',
  submit: 'Submit',
  hotelPayment: 'HotelPayment',
  findAcount: 'Find Your Account',
  enterEmail:
    'Please enter your email address or mobile number to search for your account.',
  resetPasswordText:
    'We have sent you an access code via email on your register email',
  codeHasSentTo: 'Code has sent to',
  passwordResetSuccess: 'Password reset successfully',
  emailVerified: 'Email verified successfully',
  signUpSuccess: 'Sign up successfully please login',
  guestUser: 'Guest_User',
  byPriceLowest: ' By price (lowest)',
  first: 'First',
  business: 'Business',
  ecoPremAndPrem: 'Economy Premium & Economy',
  ecoPremium: 'Economy Premium',
  economy: 'Economy',
  adults: ' Adults',
  adult: 'Adult',
  children: ' Children',
  child: 'Child',
  infants: ' Infants',
  infant: 'Infant',
  passengers: 'Passengers',
  cabin: 'Cabin',
  locations: 'locations',
  oneWayFlightSearch: 'oneWayFlightSearch',
  roundTripFlightSearch: 'roundTripFlightSearch',
  selectFlights: 'Select Flights',
  filter: 'Filter',
  price: 'Price',
  duration: 'Duration',
  flightDeparture: 'Flight Departure',
  appSlice: 'AppSlice',
  confirm: 'Confirm',
  select: 'Select',
  arriveAtDestination: 'Arrive at Destination',
  roundTripFare: 'ROUND TRIP FARE',
  onewaytripfare: 'one way trip fare',
  username: 'Username',
  default: 'default',
  darkContent: 'dark-content',
  clearAll: 'Clear all',
  cheapest: 'Cheapest',
  quickest: 'Quickest',
  apply: 'Apply',
  noAvailableFlight: 'There are no available Flights that match your criteria.',
  cancel: 'Cancel',
  ok: 'Ok',
  pleaseModify: 'Please modify your request and try again!',
  stops: 'Stops',
  nonStop: 'Non-stop',
  direct: 'Direct',
  connecting: 'Connecting',
  stop1: '1 Stop',
  stop2: '2 Stops',
  yes: 'Yes',
  MMDDYYY: 'MM/DD/YYYY',
  MDYYYY: 'M/D/YYYY',
  MMYYY: 'MM/YYYY',
  YYYYMMDD: 'YYYY-M-D',
  YYYYMD: 'YYYY-M-D',
  airline: 'Airline',
  time: 'Time',
  inBound: 'In Bound',
  outBound: 'Out Bound',
  departure: 'Departure',
  arrival: 'Arrival',
  includeAll: 'Include All',
  zero: 0,
  six: 6,
  ten: 10,
  en_US: 'en-US',
  city: 'city',
  airport: 'airport',
  nameAPI: 'name',
  end_Date: 'END_DATE',
  n: 'N',
  d: 'D',
  c: 'C',
  holdOn: 'Hold on!',
  areYouSureToGoBack: 'Are you sure you want to go back?',
  usd: 'USD',
  am_12: '12:00 am',
  pm_11_59: '11:59 pm',
  noDataFound: 'There are no available flights with your filters criteria!',
  baggageFree: "Baggage's (free)",
  bagage: 'Baggage:',
  snack: 'Snack:',
  seatAssignment: 'Seat Assignment:',
  fare: 'Fare',
  meal: 'Meal:',
  drink: 'Drink:',
  refundable: 'Refundable:',
  others: 'Others:',
  refundableTicket: 'Refundable Ticket',
  underScore: '--',
  availableSnack: 'SNACK',
  priceUSD: 'Price(USD)',
  availableMeal: 'Meal',
  flightCheckOut: 'Checkout',
  male: 'Male',
  female: 'Female',
  seatMap: 'Seat Map',
  last: 'Last',
  dob: 'Date of Birth',
  nationality: 'Nationality',
  passNumber: 'Passport Number',
  passExp: 'Passport Expiration',
  phone: 'Phone',
  unfortunatelySession: 'Unfortunately, the flight session has expired.',
  bookingPrice: 'Booking Price',
  clubAccess: 'Club Access:',
  bookflightfor: 'Book flight for',
  next: 'Next',
  nonRefundable: 'Non-Refundable',
  checkout: 'checkout',
  firstName: 'First Name',
  lastName: 'Last Name',
  countryCodePicker: 'Country Code Picker',
  active: 'active',
  cardDetails: 'Card Details',
  cardNumber: 'Card Number',
  cardExpiration: 'Card Expiration',
  cardCVC: 'Card CVC',
  not: 'Not',
  available: 'Available',
  selected: 'Selected',
  error: 'Error',
  tryAgain: 'Try Again',
  selectedSeat: 'Selected Seat',
  rowCharacteristics: 'Row Charachateristics',
  seatCharacteristics: 'Seat Charachateristics',
  overwingRow: 'Overwing Row',
  exitRow: 'Exit Row',
  preferentialBlockSeat: 'Preferential seat',
  exitRowSeat: 'Exit row seat',
  restrictedReclineSeat: 'Restricted recline seat',
  overwingSeat: 'Overwing seat',
  alreadySelectedSeat: 'Seat is already selected',
  noAvailableSeatMap: 'There is no available seat Map.',
  hotelSearch: 'Hotel Search',
  viewDeals: 'View Deals',
  hotel: 'hotels',
  propertyName: 'Property Name',
  budget: 'Budget',
  price0$: '$0',
  price5000$: '$5000+',
  togglebestrate: 'Toggle Best Rate',
  mealPlan: 'Meal Plan',
  byRating: 'By Rating',
  hotelcatergory: 'Hotel Category',
  byArea: 'By Area',
  healthandnSafety: 'Health and Safety',
  facility: 'Facilities',
  heathAndSafeData:
    'Only show properties with Enhanced Hygiene/Cleanliness protocol',
  localStarRating: 'Local Star Rating',
  room: 'Room',
  addRoom: 'Add Room',
  underline: 'underline',
  restrictedSeatGeneral: 'Restricted seat - General',
  address: 'Address',
  country: 'Country',
  zipCode: 'Zip Code',
  billingDetails: 'Billing Details',
  parking: 'Superior Studio-1 Queen Bed Free parking',
  cancellationTime: 'Free cancellation until Tuesday, 12 Sep, 2023',
  hotelPrice: '$457.00',
  seeCancellation: 'See cancellation',
  reserve: 'Reserve',
  hotelSummary: 'Hotel Summary',
  hotelDetails: 'Hotel Details',
  roomsRates: 'Rooms & Rates',
  welcome: 'Welcome',
  seatsWillAssign: 'Seats will be assigned during check-in.',
  ddmmyyyy: 'DD MMM YY',
  thankyou: 'Thank you!',
  round: 'Round',
  oneWay: 'Oneway',
  card: 'card',
  oops: 'oops!',
  sessionExpired: 'Session Expired',
  inProgress: 'In Progress',
  congratulations: 'Congratulations',
  pressOKToLogin: 'Press OK to Login!',
  nearbyPlacesAPI: "'GoogleReverseGeocoding' | 'GooglePlacesSearch'",
  mmyy: 'MM/YY',
  countryAPI: 'country',
  dollerSign: '$',
  nonRefundablefee: 'Non Refundable Payable fee',
  latitude: 'Latitude:',
  longitude: 'Longitude:',
  voice: 'Voice:',
  fax: 'Fax:',
  Category: 'Category',
  type: 'Type:',
  category: 'Category:',
  facilities: 'Facilities',
  information: 'Information',
  roomsDetails: 'Rooms Details:',
  hotelFecilities: 'Hotel Facilities',
  bookRoomFor: 'Book room for',
  special: 'Special',
  policies: 'Policies',
  checkInOut: 'Check-in / check-out:',
  guests: 'Guests',
  checkInInstructions: 'Check-in Instructions',
  guaranteeAndPayment: 'Guarantee and payment:',
  hotelServices: 'Hotel Services',
  taxInformation: 'Tax Information',
  safetyFeatures: 'Safety Features',
  diningFacilities: 'Dining Facilities',
  additionalInformation: 'Additional Information',
  freeCancellation: 'Free cancellation until',
  cancellationFee: 'Cancellation fee',
  nonRefendable: 'Non-Refundable',
  rateSummary: 'Rate Summary',
  priceforStay: 'price for stay',
  includeFeeTaxes: 'Included fee and taxes:',
  roomOccupy: 'Room occupancy',
  paymentPolicy: 'Payment Policy',
  paymentCard: 'Payment card:',
  paymentType: 'Payment guarantee type:',
  roomRateDescription: 'Room Rate/Description',
  roomOnly: 'Room Only',
  specialExtra: 'Special/extras',
  studioSuite: 'Studio - Suite',
  airConditionary: 'Air Conditionary',
  bedBreakfast: 'Bed & breakfast',
  roomNotAvailable:
    'Oops! This room is no longer available, Please choose another room',
  awsLogin: 'awslogin',
  profile: 'Profile',
  personalDetails: 'Personal Details',
  travelBookings: 'Travel bookings',
  elevation_5: 5,
  elevation_0: 0,
  fullName: 'Full Name',
  phoneNumber: 'Phone Number',
  save: 'Save',
  City: 'City',
  stays: 'Stays',
  us: 'us',
  blog: 'Blog',
  MMMMDDYYYY: 'MMMM DD,YYYY',
  DDMMMYY: 'DDMMMYY',
  CHD: 'CHD',
  ADT: 'ADT',
  INF: 'INF',
  M: 'M',
  F: 'F',
  T000000000Z: 'T00:00:00.000Z',
  theSmartWayToTravel: 'The smart way to travel',
  done: 'Done',
  InformationtextForHotelCheckout: 'Please fill the below information',
};

// validation text..
export const validations = {
  enterEmail: '* Please enter email',
  enterPassword: '* Please enter password',
  enterValidEmail: '* Please enter valid email',
  enterValidPassword: '* Please enter valid password',
  enterName: '* Please enter username',
  enterConfirmPassword: '* Please enter confirm password',
  passwordAndConfirmPasswordSame: '* Must be same as password',
  shortName: 'Username is too short',
  passwordMustBe:
    'Password must be eight characters including one uppercase letter, one special character and alphanumeric characters',
  enterOTP: 'Please enter six digit OTP',
  enterValidOTP: 'Please enter valid OTP',
  selectLocation: '* Please select location',
  selectDate: '* Please select date',
  onlyCharacters: '* Only characters are allowed',
  enterFirstName: '* Please enter first name',
  tooShort: 'Too short',
  enterLastName: '* Please enter last name',
  enterDob: '* Please enter date of birth',
  enterNationality: '* Please enter nationality',
  enterPassNumber: '* Please enter passport number',
  enterPassExpiry: '* Please enter passport expiration',
  enterPhone: '* Please enter phone number',
  enterValidPhone: '* Please enter valid phone number',
  enterValidDateFormat: '* Please enter valid date format (MM/DD/YYYY)',
  enterValidPassportNumber: '* Please enter valid passport number',
  enterAddress: '* Please enter your address',
  enterCountry: '* Please enter your country',
  enterCity: '* Please enter your city',
  enterZipCode: '* Please enter your zip code',
  enterCardNumber: '* Please enter your card number',
  enterValiddCardNumber: '* Please enter a valid card number',
  enterCardExpiration: '* Please enter date',
  enterValidCardExpiration: '* Please enter valid card expiration date',
  enterCardCVC: '* Please enter card CVV',
  enterValidCardCVV: '* Please enter valid card CVV',
  selectGender: '* Please Select gender',
  selectCountryCode: '@ Please select country code',
  depDateNotGreaterThenRetDate:
    "Departure date should'nt be greater then return date",
  checkInDateNotGreaterThenCheckout:
    'Check in date should not be greater then checkout date',
};

// Constants for the AWS errors
export const awsError = {
  userNotConfirmed: 'User is not confirmed.',
};

// Constants for the flash messages
export const flashMessageConstants = {
  success: 'success',
  danger: 'danger',
  info: 'info',
};

// Constant for the status code
export const statusCode = {
  Code_200: 200,
  Code_500: 500,
  code_102: '102',
  code_422: 422,
};

// URL of the carriers
export const carriersURL = {
  imgURL: 'https://www.skyscanner.net/images/airlines/small/',
  png: '.png',
};

// Constants for the persist keys to blacklist
export const persistKeys = {
  flightState: 'flightState',
  oneWayFlightState: 'oneWayFlightState',
  roundTripFlightState: 'roundTripFlightState',
  appSliceState: 'appSliceState',
  checkoutState: 'checkoutState',
  seatMapState: 'seatMapState',
  hotelState: 'hotelState',
  submitState: 'submitState',
  nationalityState: 'nationalityState',
  hotelDetailsState: 'hotelDetailsState',
  roomRatesState: 'roomRatesState',
  roomReserveState: 'roomReserveState',
  hotelPaymentState: 'hotelPaymentState',
  awsLoginState: 'awsLoginState',
};

export const sessionOutConstants = {
  priceChanged:
    'Unfortunately, session expired price has changed please select another flight',
  flightNumberChanged:
    'Unfortunately, session expired flight number has changed please select another flight',
  priceChangedforHotel:
    'Unfortunately, session expired price has changed please select another hotel',
};

export const seatCodes = {
  O: 'O',
  _1D: '1D',
  K: 'K',
  E: 'E',
  _1: '1',
  F: 'F',
  Z: 'Z',
  S: 'S',
  CH: 'CH',
  A: 'A',
  _8: '8',
};

export const errorMessage = {
  errorText:
    'There are no available Hotels that match your criteria. Please modify your request and try again!',
};

export const flagURL = {
  flaghhtp: 'https://flagcdn.com/h20/',
  wedp: '.webp',
};

export const graphQLConstants = {
  https: 'https:',
};
