/* eslint-disable prettier/prettier */
// Navigation constants
export default {
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  HOME: 'HOME',
  OTP: 'OTP',
  FORGOT_PASSWORD: 'FORGOTPASSWORD',
  RESET_PASSWORD: 'RESETPASSWORD',
  HOTEL: 'HOTEL',
  HOTEL_LIST: 'HOTELLIST',
  FLIGHT: 'Flight',
  SEARCH: 'SEARCH',
  CAR: 'CAR',
  HOTEL_TAB: 'HOTELTAB',
  FLIGHT_TAB: 'FLIGHTTAB',
  CAR_TAB: 'CARTAB',
  SIGN_IN_UP: 'Signin/signup',
  MainStack: 'MainStack',
  FLIGHT_SEARCH: 'FlightSearch',
  DRAWER_PROFILE: 'Profile',
  DRAWER_PROTECTION: 'Protection',
  DRAWER_PRIVACYPOLICY: 'Privacy-Policy',
  DRAWER_TERMSANDCONDITION: 'Terms & Conditions',
  DRAWER_BLOG: 'Blog',
  DRAWER_ABOUTUS: 'About Us',
  DRAWER_CONTACTUS: 'Contact Us',
  MIANSTACK: 'MainStack',
  CHECKOUT: 'CHECKOUT',
  PAYMENT: 'PAYMENT',
  HOTEL_RATING: 'HOTEL_RATING',
  HOTEL_RESERVE: 'HOTEL_RESERVE',
  HOTEL_CHECKOUT: 'HOTEL_CHECKOUT',
  HOTEL_PAYMENT: 'HOTEL_PAYMENT',
  LOGIN_SIGNUP: 'Log in / Sign Up',
  BLOG: 'BLOG',
  HOTEL_PAYMENT_RESERVATION:'HOTEL_PAYMENT_RESERVATION',
};

export const TabBarConstants = {
  HOME: 'Home',
  HOTELS: 'Hotels',
  FLIGHTS: 'Flights',
  CARS: 'Cars',
};
