/* eslint-disable prettier/prettier */
import { Fonts } from '@src/assets';
import colors from '@src/constants/colors';
import { Platform, StyleSheet } from 'react-native';
import {
  responsiveFontSize,
  responsiveHeight,
  responsiveWidth,
} from 'react-native-responsive-dimensions';

export default StyleSheet.create({
  containerStyle: { backgroundColor: 'white', flex: 1 },
  contentContainerStyle: {
    // flex: 1,
    backgroundColor: colors.color_fff,
  },
  headerLeftIconStyle: {
    tintColor: colors.color_000,
    height: responsiveWidth(9),
    width: responsiveWidth(9),
  },
  headerLabelStyle: {
    color: colors.color_000,
    fontWeight: '500',
    fontSize: responsiveFontSize(2),
    fontFamily: Fonts.ROBOTO_REGULAR,
  },
  profileDetailsContainerStyle: {
    height: responsiveHeight(25),
    width: responsiveWidth(80),
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: Platform.OS === 'ios' ? responsiveHeight(-3) : 0,
  },
  profileImageStyle: {
    width: responsiveWidth(30),
    height: responsiveWidth(30),
    borderRadius: responsiveWidth(15),
  },
  nameTextStyle: {
    color: colors.color_000,
    fontWeight: '500',
    fontFamily: Fonts.ROBOTO_REGULAR,
    fontSize: responsiveFontSize(2),
  },
  emailTextStyle: {
    color: colors.color_8A8A8A,
    fontSize: responsiveFontSize(1.5),
    fontWeight: '400',
    fontFamily: Fonts.ROBOTO_REGULAR,
    marginTop: 5,
  },
  detailsContainerStyle: {
    height: responsiveHeight(6.5),
    backgroundColor: colors.color_F9F9F9,
    width: responsiveWidth(90),
    alignSelf: 'center',
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  deatilsButtonStyle: {
    flexDirection: 'row',
    width: responsiveWidth(42),
    height: responsiveHeight(5.5),
    borderRadius: 5,
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  buttonTextStyle: {
    fontSize: responsiveFontSize(1.8),
    fontWeight: '400',
    fontFamily: Fonts.ROBOTO_REGULAR,
  },
  mainContainerCustomStyle: {
    marginTop: 20,
  },
  countryCityContainerStyle: {
    flexDirection: 'row',
    width: responsiveWidth(84),
    alignSelf: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  countryCitySubContainerStyle: {
    borderWidth: 1,
    width: responsiveWidth(38),
    height: responsiveHeight(8),
    borderRadius: 9,
    borderColor: colors.color_EEEEEE,
    paddingHorizontal: responsiveWidth(2),
    justifyContent: 'space-evenly',
  },
  countryCityTextStyle: {
    fontSize: 14,
    color: colors.color_8B8B8B,
    marginTop: responsiveHeight(0.5),
  },
  countryContainerStyle: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  textInputsStyle: {
    fontSize: responsiveFontSize(2),
    fontFamily: Fonts.ROBOTO_REGULAR,
    bottom: Platform.OS === 'ios' ? -10 : null,
    color: colors.color_000,
    flex: 1,
    height: responsiveHeight(4),
    marginLeft: responsiveWidth(1),
    // marginVertical: responsiveHeight(-1.0),
    marginBottom: responsiveHeight(-1.0),
  },
  secondTextInput: {
    flex: 1,
  },
  travelBookingContainerStyle: {
    backgroundColor: colors.color_F9F9F9,
    width: responsiveWidth(90),
    alignSelf: 'center',
    marginVertical: responsiveHeight(2),
  },
  bookingTextContainerStyle: {
    width: responsiveWidth(90),
    height: responsiveHeight(7),
    backgroundColor: colors.color_fff,
    alignSelf: 'center',
    elevation: 0.5,
    margin: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: responsiveWidth(2),
    alignItems: 'flex-end',
  },
  travelBookingTouchableContainerStyle: {
    width: responsiveWidth(29),
    height: responsiveHeight(6),
    borderTopLeftRadius: 13,
    borderTopRightRadius: 13,
    justifyContent: 'space-between',
  },
  travelImgTextContainerStyle: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    height: responsiveHeight(5),
    width: responsiveWidth(20),
    alignSelf: 'center',
  },
  bottomSlideViewStyle: {
    width: responsiveWidth(15),
    borderWidth: 3,
    borderColor: colors.color_0094E6,
    alignSelf: 'center',
    borderRadius: 15,
  },
  bookingTextStyle: {
    textTransform: 'capitalize',
    color: colors.color_000,
    fontWeight: '500',
    fontFamily: Fonts.ROBOTO_REGULAR,
    fontSize: responsiveFontSize(1.8),
  },
  carBookingDetailContainerStyle: {
    height: responsiveHeight(40),
    backgroundColor: colors.color_fff,
    alignItems: 'center',
    justifyContent: 'center',
  },
  comingSoonTextStyle: {
    color: colors.color_000,
    fontWeight: '500',
  },
  imageBackground: {
    flex: 1,
  },
  avatar: {
    alignItems: 'center',
    // marginTop: '40%',
  },
  avatarImage: {
    height: 260,
    width: 260,
    overflow: 'hidden',
    borderColor: '#ffffff',
    borderWidth: 4,
    borderRadius: 260 / 2,
  },
  addButton: {
    height: 40,
    width: 40,
    backgroundColor: '#f2f2fC',
    borderRadius: 50,
    position: 'absolute',
    // right: 104,
    bottom: 5,
  },
  addButtonIcon: {
    height: 40,
    width: 40,
  },
  usernameText: {
    fontSize: 24,
    fontWeight: '700',
    color: '#ffffff',
    marginTop: 12,
  },
  modal: {
    justifyContent: 'flex-end',
    margin: 0,
  },
  buttonIcon: {
    width: 30,
    height: 30,
    margin: 10,
  },
  buttons: {
    backgroundColor: 'white',
    flexDirection: 'row',
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
    height:100,
  },
  button: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    fontSize: 14,
    fontWeight: '600',
  },
});
