/* eslint-disable prettier/prettier */
import {Fonts} from '@src/assets';
import colors from '@src/constants/colors';
import {StyleSheet} from 'react-native';
import {
  responsiveFontSize,
  responsiveHeight,
  responsiveWidth,
} from 'react-native-responsive-dimensions';

// common styles..
export default StyleSheet.create({
  container: {
    flex: 1,
  },
  keyboardAwareStyle: {
    flexGrow: 1,
    marginVertical: responsiveHeight(2),
    marginHorizontal: responsiveWidth(4),
    paddingVertical: responsiveHeight(3),
  },
  errorTextStyle: {
    color: colors.color_red,
    marginLeft: 12,
  },
  backgroundImage: {
    flex: 1,
  },
  signTextHeader: {
    fontSize: responsiveFontSize(3.5),
    fontWeight: '600',
    color: colors.color_fff,
    marginTop: responsiveHeight(2),
    fontFamily: Fonts.JAKARTA_BOLD,
  },
  signTextSubHeader: {
    fontSize: responsiveFontSize(2.2),
    width: responsiveWidth(95),
    color: colors.color_fff,
    marginTop: responsiveWidth(2),
    fontFamily: Fonts.JAKARTA_REGULAR,
  },
  welcomeTextContainer: {
    width: responsiveWidth(62),
    marginTop: responsiveHeight(3),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  welcomeTextStyle: {
    fontSize: responsiveFontSize(2.5),
    color: colors.color_fff,
    fontFamily: Fonts.JAKARTA_REGULAR,
  },
  travelClubTextContainer: {
    backgroundColor: colors.color_transpShadow,
    width: responsiveWidth(32),
    height: responsiveHeight(6),
    borderRadius: responsiveWidth(5),
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    // opacity: colors.opacity,
  },
  travelClubTextStyle: {
    fontSize: responsiveFontSize(2.2),
    color: colors.color_fff,
    fontFamily: Fonts.JAKARTA_REGULAR,
  },
  iQTextStyle: {
    fontSize: responsiveFontSize(2.2),
    color: colors.color_darkBlue,
    fontFamily: Fonts.JAKARTA_REGULAR,
  },
  accountTagLineContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: responsiveHeight(3),
  },
  accountTextStyle: {
    color: colors.color_fff,
    fontFamily: Fonts.JAKARTA_REGULAR,
  },
  signNowTextStyle: {
    marginLeft: 2,
    fontSize: 15,
    color: colors.color_0094E6,
    fontFamily: Fonts.JAKARTA_REGULAR,
  },
  ticketContainer_1: {
    backgroundColor: colors.color_fff,
    borderRadius: responsiveWidth(8),
    alignSelf: 'center',
    width: responsiveWidth(95),
    margin: responsiveHeight(2),
    elevation: 1,
    padding: responsiveHeight(1),
  },
  codeStyle: {
    flexDirection: 'row',
    width: responsiveWidth(80),
    justifyContent: 'space-between',
    marginTop: responsiveHeight(1.5),
    marginLeft: responsiveWidth(5),
    alignSelf: 'center',
  },
  codeTextStyle: {
    fontSize: responsiveFontSize(2.5),
    fontFamily: Fonts.ROBOTO_REGULAR,
    fontWeight: '500',
    letterSpacing: 0.42,
    color: colors.color_000,
  },
  cityNamesStyle: {
    flexDirection: 'row',
    marginLeft: responsiveWidth(5),
    width: responsiveWidth(80),
    alignSelf: 'center',
    justifyContent: 'space-between',
  },
  cityTextStyle: {
    color: colors.color_8B8B8B,
    fontWeight: '400',
    letterSpacing: 0.325,
    fontFamily: Fonts.ROBOTO_REGULAR,
  },
  airportDepartureTextStyle: {
    // flex: 0.4,
  },
  cityTimeTextStyle: {
    color: colors.color_0068D2,
    // textAlign: 'left',
    // flex: 0.32,
  },
  arrivalCityTextStyle: {
    // flex: 0.25,
    // textAlign: 'left',
  },
  timeLineStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: responsiveHeight(1.5),
    alignSelf: 'center',
    width: responsiveWidth(80),
    justifyContent: 'space-between',
  },
  timeTextStyle: {
    fontSize: responsiveFontSize(2),
    color: colors.color_000,
    fontFamily: Fonts.ROBOTO_REGULAR,
    fontWeight: '500',
    letterSpacing: 0.32,
  },
  timeLineContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ticketTimeLineStyle: {
    width: responsiveWidth(30),
  },
  ticketTimePlaneStyle: {
    position: 'absolute',
  },
  airwaysContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: responsiveHeight(0),
  },
  ticketAirwaysLogo: {
    height: 35,
    width: 75,
  },
  airwaysTextStyle: {
    color: colors.color_B2B2B2,
    marginLeft: responsiveWidth(1),
    fontSize: 13,
    fontWeight: '400',
    fontFamily: Fonts.ROBOTO_REGULAR,
    letterSpacing: 0.26,
    textTransform: 'capitalize',
  },
  buttonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: responsiveWidth(80),
    marginTop: responsiveHeight(2),
    alignSelf: 'center',
  },
  priceTextStyle: {
    fontSize: responsiveFontSize(2),
    color: colors.color_0355A8,
    fontFamily: Fonts.ROBOTO_REGULAR,
    fontWeight: '500',
    letterSpacing: 0.36,
  },
  tripFareTextStyle: {
    color: colors.color_B2B2B2,
    fontWeight: '400',
    textTransform: 'uppercase',
    fontSize: responsiveFontSize(1.3),
    letterSpacing: 0.22,
    fontFamily: Fonts.ROBOTO_REGULAR,
  },
  buttonTextStyle: {
    fontSize: responsiveFontSize(1.7),
    fontFamily: Fonts.ROBOTO_REGULAR,
    fontWeight: '400',
    letterSpacing: 0.26,
  },
  selectButtonGradientStyle: {
    width: 93,
    height: 32,
    borderRadius: 5,
    flexShrink: 0,
  },
  roundView: {
    backgroundColor: colors.color_f2f2f2,
    height: responsiveWidth(6),
    width: responsiveWidth(6),
    borderRadius: responsiveWidth(10),
    position: 'absolute',
    flexShrink: 0,
    alignSelf: 'flex-end',
    top: responsiveHeight(15),
    right: -2,
  },
  subRoundViewStyle: {
    alignSelf: 'flex-start',
    left: -2,
  },
  lineStyle: {
    position: 'absolute',
    top: responsiveHeight(16.5),
    alignSelf: 'center',
    width: responsiveWidth(84),
  },
  ticketDropdownContainerStyle: {
    height: responsiveWidth(8),
    width: responsiveWidth(8),
    backgroundColor: colors.color_fff,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: responsiveWidth(10),
    alignSelf: 'center',
    top: responsiveHeight(2),
  },
  ticketDropupContainerStyle: {
    height: responsiveWidth(8),
    width: responsiveWidth(8),
    backgroundColor: colors.color_fff,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: responsiveWidth(10),
    alignSelf: 'center',
    top: responsiveHeight(2),
  },
  ticketDropdownStyle: {
    height: responsiveWidth(4),
    width: responsiveWidth(4),
    borderColor: 'white',
  },
  ticketDropupStyle: {
    height: responsiveWidth(4),
    width: responsiveWidth(4),
  },
  departureTextStyle: {
    color: colors.color_0355A8,
    fontSize: responsiveFontSize(2),
    fontFamily: Fonts.ROBOTO_REGULAR,
    fontWeight: '500',
    marginLeft: responsiveWidth(5),
    marginTop: responsiveHeight(1.5),
    letterSpacing: 0.32,
  },
  departureTimeStyle: {
    marginLeft: responsiveWidth(18),
    marginTop: responsiveHeight(1.5),
    fontSize: responsiveFontSize(1.5),
  },

  departureLineContainer: {
    marginLeft: responsiveWidth(25),
    position: 'absolute',
  },
  ticketDepartureLineStyle: {
    marginTop: responsiveHeight(35),
  },

  ticketCalendarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: responsiveWidth(21.5),
    marginTop: responsiveHeight(2),
    zIndex: 1,
  },
  dateTextStyle: {
    color: colors.color_636363,
    fontFamily: Fonts.ROBOTO_REGULAR,
    marginLeft: responsiveWidth(2.5),
    fontSize: responsiveFontSize(1.5),
    fontWeight: '400',
  },
  flightStationContainer: {
    width: responsiveWidth(85),
    borderWidth: 0.5,
    borderColor: colors.color_EBEBEB,
    alignSelf: 'center',
    marginTop: responsiveHeight(2),
    paddingHorizontal: 5,
  },
  busStationContainer: {
    flexDirection: 'row',
    marginTop: responsiveHeight(1),
    marginLeft: responsiveWidth(3),
    margin: responsiveHeight(1),
    width: responsiveWidth(70),
  },
  stationTimeTextStyle: {
    color: colors.color_000,
    fontWeight: '500',
    fontSize: responsiveFontSize(1.6),
    fontFamily: Fonts.ROBOTO_REGULAR,
    marginRight: 3,
  },
  stationTextStyle: {
    fontSize: responsiveFontSize(1.5),
    color: colors.color_9e9e9e,
    maxWidth: responsiveWidth(60),
    marginLeft: 5,
  },
  downPlaneStyle: {
    marginRight: 5,
  },
  cabinContainer: {
    height: 28,
    backgroundColor: colors.color_transparentBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cabinTextStyle: {
    color: colors.color_0094E6,
    right: responsiveWidth(10),
    fontFamily: Fonts.ROBOTO_REGULAR,
  },
  flightContainer: {
    flexDirection: 'row',
    backgroundColor: colors.color_F9F9F9,
    alignItems: 'center',
    flexWrap: 'wrap',
    paddingVertical: 5,
  },
  flightTextStyle: {
    backgroundColor: colors.color_fff,
    height: 30,
    fontSize: responsiveFontSize(1.5),
    color: colors.color_000,
    textAlign: 'center',
    borderWidth: 0.5,
    textAlignVertical: 'center',
    borderColor: colors.color_C8C5C5,
    borderRadius: 10,
    marginLeft: responsiveWidth(1),
    fontFamily: Fonts.JAKARTA_REGULAR,
    fontWeight: '400',
    padding: 4,
  },
  flightLogoStyle: {
    marginHorizontal: responsiveWidth(2),
    height: 30,
    width: 60,
  },
  arriveDestinationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: responsiveHeight(1),
  },
  ticketArriveLocationStyle: {
    right: responsiveWidth(0),
    left: responsiveWidth(3),
  },
  arriveAtDestiStyle: {
    fontFamily: Fonts.ROBOTO_REGULAR,
    color: colors.color_AFAFAF,
    fontWeight: '400',
    letterSpacing: 0.32,
    marginLeft: 10,
    marginVertical: responsiveHeight(0.5),
  },
  destinationTextStyle: {
    color: colors.color_000,
    fontFamily: Fonts.ROBOTO_REGULAR,
    fontWeight: '500',
    fontSize: responsiveFontSize(2),
    marginLeft: 10,
  },
  destinationTextContainer: {
    left: responsiveWidth(3),
    width: responsiveWidth(50),
  },
  filterHeaderContainerStyle: {
    width: responsiveWidth(95),
    borderWidth: 1,
    alignSelf: 'center',
    flexShrink: 0,
    borderRadius: 16,
    marginTop: responsiveHeight(2),
    padding: responsiveHeight(2),
    borderColor: colors.color_F6F6F6,
  },
  codeStyleSubView: {width: responsiveWidth(20)},
  calendarTextStyle: {
    color: colors.color_000,
  },
});
