/* eslint-disable prettier/prettier */
import { Dimensions, Platform, StyleSheet } from 'react-native';
import colors from '@src/constants/colors';
// import { Fonts } from '@src/assets';
import {
  responsiveWidth,
  responsiveHeight,
  responsiveFontSize,
} from 'react-native-responsive-dimensions';

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
  scrollViewContainer: {
    backgroundColor: '#fff',
  },
  hotelButton: {
    width: 80,
    height: 80,
    borderRadius: 80,
    backgroundColor: '#e0ce9d',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
    borderColor: 'grey',
  },
  indicatorContainer: {
    position: 'absolute',
    flexDirection: 'row',
    right: 10,
    top: 60 * 4 + 10,
  },
  circleIndicatorView: {
    height: 5,
    borderRadius: 5,
    marginHorizontal: 2,
  },
  circleIndicatorView1: {
    height: 5,
    borderRadius: 15,
    marginHorizontal: 2,
  },

  locationTextStyle: {
    color: 'white',
    fontSize: responsiveFontSize(1.5),
    fontWeight: '600',
    width: responsiveWidth(45),
  },
  imageBoxContainer: {
    position: 'absolute',
    right: 10,
    top: 20,
  },
  priceContainer: {
    position: 'absolute',
    right: 10,
    top: responsiveHeight(32),
  },
  imageBox: {
    width: 60,
    height: 60,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: 'white',
    marginVertical: 5,
  },
  tintImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: 'white',
    marginVertical: 5,
    tintColor: 'rgba(0,0,0,0.65)',
  },
  textContainer: {
    position: 'absolute',
    alignSelf: 'center',
    backgroundColor: 'rgba(0,0,0,0.65)',
    padding: 10,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    paddingHorizontal: 10,
  },
  titleTextStyle: {
    transform: [{ rotate: '-18deg' }],
    color: '#000',
    textAlign: 'center',
  },
  circleButtonStyle: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '80%',
    transform: [{ rotate: '19deg' }],
    position: 'absolute',
    top: Platform.OS === 'ios' ? height / 2.4 : height / 2.5,
    left: 0,
  },
  carouselView: {
    height: height / 2.1,
    width: width,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomRightRadius: 20,
    overflow: 'hidden',
  },
  image: {
    width: width,
    height: '100%',
    borderBottomRightRadius: 20,
  },
  triangle: {
    width: 0,
    height: 0,
    borderStyle: 'solid',
    borderTopWidth: 130,
    borderLeftWidth: 360,
    borderLeftColor: '#fff',
    borderTopColor: 'transparent',
    position: 'absolute',
    left: 0,
    bottom: 0,
    zIndex: 50,
  },
  borderCardView: {
    borderColor: colors.color_hotelBC,

    borderWidth: 5,
    // height: height / 3,
    margin: 20,
    borderRadius: 37,
    opacity: 3,
    marginTop: responsiveHeight(18),
  },
  imageBorder: {
    borderWidth: 8,
    borderColor: colors.color_fff,
    height: responsiveHeight(20),
    width: responsiveWidth(81),
    borderRadius: 25,
    marginTop: height / -16,
    marginHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'red',
  },
  imageRactangle: {
    height: responsiveHeight(21),
    width: responsiveWidth(81),
    // alignSelf: 'center',
    borderRadius: 25,
    borderWidth: 8,
    borderColor: colors.color_fff,
    // marginTop: responsiveHeight(50),
    // borderWidth: 8,
    // position:'absolute',
  },
  iconsView: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    justifyContent: 'space-between',
    marginTop: 10,
  },
  wifiIcon: {
    alignSelf: 'center',
  },
  parkingTxt: {
    fontSize: 17,
    fontWeight: '500',
    color: colors.color_000,
    alignSelf: 'center',
    marginTop: 10,
  },
  cancellationDateTxt: {
    color: colors.color_17C954,
    fontWeight: '500',
    fontSize: 11,
  },
  pricesView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 20,
  },
  priceTxt: {
    color: colors.color_2D180D,
    fontWeight: '700',
    fontSize: 26,
  },
  cancellationTxt: {
    fontWeight: '400',
    fontSize: 12,
    color: colors.color_000000,
    // textDecorationLine:'underline',
  },
  line: {
    height: 1.5,
    backgroundColor: colors.color_9e9e9e,
    width: '92%',
  },
  buttonStyle: {
    width: responsiveWidth(30),
    alignSelf: 'center',
    borderRadius: responsiveWidth(3),
    height: responsiveHeight(5.5),
  },
  labelStyle: {
    fontSize: 16,
  },
  wifiIconView: {
    height: 25,
    width: 25,
    borderWidth: 1.5,
    borderColor: colors.color_EBEBEB,
    alignSelf: 'center',
    justifyContent: 'center',
    borderRadius: 6,
  },
  cancellationTimeView: {
    height: 30,
    borderWidth: 1.5,
    borderColor: colors.color_EBEBEB,
    justifyContent: 'center',
    borderRadius: 6,
    paddingHorizontal: 5,
  },
  txtView: {
    marginTop: responsiveHeight(13),
  },
  ractangleCrouselView: {
    position: 'absolute',
    marginTop: responsiveHeight(-8),
  },
  dotStyle: {
    width: 10,
    height: 10,
    borderRadius: 5,
    alignSelf: 'center',
    backgroundColor: colors.color_fff,
  },
  paginationStyle: {
    marginTop: responsiveHeight(-8),
    marginRight: responsiveHeight(14),
  },
  location: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 2,
  },
  locationlogo: {
    tintColor: colors?.color_F9935C,
    marginRight: 8,
    resizeMode: 'contain',
    height: responsiveHeight(2),
    width: responsiveWidth(5),
  },
  locationText: {
    fontSize: responsiveFontSize(1.6),
    color: colors.color_888888,
    width: responsiveWidth(45),
  },
  ratingMainView: {
    flexDirection: 'row',
  },
  ratingImage: {
    height: responsiveHeight(1.8),
    marginHorizontal: 3,
  },
  roomPrice: {
    fontSize: responsiveFontSize(2.5),
    fontWeight: '800',
    marginVertical: 2,
    color: colors?.color_fff,
  },
  roomdesc: {
    fontSize: responsiveFontSize(2),
    marginVertical: 2,
    color: colors?.color_fff,
  },
  roomDescView: {
    alignItems: 'flex-end',
  },
  headerLeftIconStyle: {
    height: 17,
    width: 17,
    tintColor: colors.color_000,
    backgroundColor: colors.color_D9D9D9,
    borderRadius: 10,
    padding: 17,
    marginHorizontal: 10,
  },
  backButton: {
    position: 'absolute',
  },
  thirdImage: {
    position: 'absolute',
    top: 25,
    left: 18,
  },
  imageTextStyle: {
    color: colors.color_fff,
    fontSize: 15,
    fontWeight: '400',
  },
  tabBarStyle: {
    height: responsiveHeight(9),
    width: responsiveWidth(95),
    alignSelf: 'center',
    marginTop: 5,
    marginHorizontal: Platform.OS === 'android' ? 0 : 10,
    marginBottom: Platform.OS === 'android' ? responsiveHeight(0.5) : 20,
    borderRadius: 25,
    backgroundColor: colors.color_fff,
    shadowColor: colors.color_000,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.17,
    shadowRadius: 3.05,
    elevation: 4,
  },
  secondView: { marginTop: Platform.OS === 'ios' ? responsiveHeight(15) : responsiveHeight(10), bottom: 10 },
  headerLabelStyle: {
    color: colors.color_fff,
    fontWeight: '500',
    fontSize: 16,
    flexShrink: 0,
  },
  loaderStyle: {
    backgroundColor: colors.color_whiteTransparent,
  },
  closeButton: {
    alignSelf: 'flex-end',
    backgroundColor: colors.color_fff,
    marginRight: responsiveWidth(5),
    height: responsiveWidth(10),
    width: responsiveWidth(10),
    borderRadius: responsiveWidth(10),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: responsiveHeight(1),
  },
  Modalimage: {
    height: responsiveHeight(25),
    margin: 5,
  },
});
