/* eslint-disable prettier/prettier */
export const facilitiesCodes = [
  {text: 'Adjoining rooms', matIcon: 'meeting_room', shText: 'Adjoin rooms'},
  {text: 'Air conditioning', matIcon: 'ac_unit', shText: 'AC'},
  {text: 'Alarm clock', matIcon: 'alarm', shText: 'Alarm'},
  {text: 'All news channel', matIcon: 'live_tv', shText: 'News channel'},
  {text: 'AM/FM radio', matIcon: 'radio', shText: 'Radio'},
  {
    text: 'Baby listening device',
    matIcon: 'perm_device_inforngIconion',
    shText: 'Baby tunes',
  },
  {
    text: 'Balcony/Lanai/Terrace',
    matIcon: 'calendar_view_day',
    shText: 'Terrace',
  },
  {text: 'Barbeque grills', matIcon: 'border_left', shText: 'Barbeque'},
  {text: 'Bath tub with spray jets', matIcon: 'hot_tub', shText: 'Bath tub'},
  {text: 'Bathrobe', matIcon: 'confirngIconion_number', shText: 'Bathrobe'},
  {text: 'Bathroom amenities', matIcon: 'hot_tub', shText: 'Bath Amenities'},
  {
    text: 'Bathroom telephone',
    matIcon: 'speaker_phone',
    shText: 'Bath telephone',
  },
  {text: 'Bathtub', matIcon: 'hot_tub', shText: 'Bathtub'},
  {text: 'Bathtub only', matIcon: 'hot_tub', shText: 'Bathtub only'},
  {text: 'Bathtub/shower combination', matIcon: 'hot_tub', shText: 'shower'},
  {text: 'Bidet', matIcon: 'kitchen', shText: 'Bidet'},
  {text: 'Bottled water', matIcon: 'gradient', shText: 'Bottled wate'},
  {text: 'Cable television', matIcon: 'swap_calls', shText: 'Cable'},
  {text: 'Coffee/Tea maker', faIcon: 'faCoffee', shText: 'Coffee'},
  {text: 'Color television', faIcon: 'faTv', shText: 'television'},
  {text: 'Computer', matIcon: 'computer', shText: 'Computer'},
  {
    text: 'Connecting rooms',
    matIcon: 'cast_connected',
    shText: 'Connecting rooms',
  },
  {
    text: 'Converters/ Voltage adaptors',
    matIcon: 'device_hub',
    shText: 'Converters',
  },
  {text: 'Copier', matIcon: 'file_copy', shText: 'Copier'},
  {
    text: 'Cordless phone',
    matIcon: 'record_voice_over',
    shText: 'Cordless phone',
  },
  {text: 'Cribs', faIcon: 'faScribd', shText: 'Cribs'},
  {text: 'Data port', matIcon: 'compare_arrows', shText: 'Data port'},
  {text: 'Desk', matIcon: 'desktop_mac', shText: 'Desk'},
  {text: 'Desk with lamp', matIcon: 'table_chart', shText: 'Desk with lamp'},
  {text: 'Dining guide', matIcon: 'local_dining', shText: 'Dining guide'},
  {
    text: 'Direct dial phone number',
    matcon: 'phone_forwarded',
    shText: 'phone services',
  },
  {text: 'Dishwasher', faIcon: 'faShower', shText: 'Dishwasher'},
  {text: 'Double beds', faIcon: 'faBed', shText: 'Double beds'},
  {
    text: 'Dual voltage outlet',
    matIcon: 'format_align_center',
    shText: 'Dual voltage',
  },
  {
    text: 'Electrical current voltage',
    matIcon: 'show_chart',
    shText: 'Electrical voltage',
  },
  {text: 'Ergonomic chair', faIcon: 'faWheelchair', shText: 'Ergonomic chair'},
  {
    text: 'Extended phone cord',
    matIcon: 'phonelink_ring',
    shText: 'phone cord',
  },
  {text: 'Fax machine', faIcon: 'faFax', shText: 'Fax machine'},
  {text: 'Fire alarm', matIcon: 'alarm_on', shText: 'Fire alarm'},
  {
    text: 'Fire alarm with light',
    matIcon: 'access_alarm',
    shText: 'Fire alarm',
  },
  {text: 'Fireplace', matIcon: 'whatshot', shText: 'Fireplace'},
  {text: 'Free toll free calls', matIcon: 'crop_free', shText: 'Free toll '},
  {text: 'Free calls', matIcon: 'crop_free', shText: 'Free calls'},
  {
    text: 'Free credit card access calls',
    faIcon: 'faCreditCard',
    shText: 'Free credit card',
  },
  {
    text: 'Free local calls',
    matIcon: 'local_phone',
    shText: 'Free local calls',
  },
  {text: 'Free movies/video', matIcon: 'movie', shText: 'movies/video'},
  {text: 'Full kitchen', matIcon: 'meeting_room', shText: 'kitchen'},
  {text: 'Grab bars in bathroom', faIcon: 'faToilet', shText: 'Grab bars'},
  {text: 'Grecian tub', faIcon: 'faHotTub', shText: 'Grecian tub'},
  {text: 'Hairdryer', faIcon: 'faUser', shText: 'Hairdryer'},
  {
    text: 'High speed internet connection',
    matIcon: 'signal_cellular_alt',
    shText: 'Free Internet',
  },
  {text: 'Interactive web TV', matIcon: 'tv', shText: 'web TV'},
  {
    text: 'International direct dialing',
    matIcon: 'format_textdirection_l_to_r',
    shText: 'International dialing',
  },
  {text: 'Internet access', matIcon: 'assessment', shText: 'Internet access'},
  {text: 'Iron', faIcon: 'faAtom', shText: 'Iron'},
  {text: 'Ironing board', faIcon: 'faTable', shText: 'Ironing board'},
  {text: 'Whirpool', matIcon: 'pages', shText: 'Whirpool'},
  {text: 'King bed', matIcon: 'spa', shText: 'King bed'},
  {text: 'Kitchen', matIcon: 'meeting_room', shText: 'Kitchen'},
  {text: 'Kitchen supplies', matIcon: 'sync', shText: 'Kitchen supplies'},
  {text: 'Kitchenette', matIcon: 'zoom_out_map', shText: 'Kitchenette'},
  {text: 'Knock light', matIcon: 'donut_small', shText: 'Knock light'},
  {text: 'Laptop', matIcon: 'laptop', shText: 'Laptop'},
  {text: 'Large desk', matIcon: 'table_chart', shText: 'Large desk'},
  {text: 'Large work area', matIcon: 'group_work', shText: 'work area'},
  {
    text: 'Laundry basket/clothes hamper',
    faIcon: 'faHammer',
    shText: 'clothes basket',
  },
  {text: 'Loft', matIcon: 'find_replace', shText: 'Loft'},
  {text: 'Microwave', matIcon: 'picture_in_picture_alt', shText: 'Microwave'},
  {text: 'Minibar', matIcon: 'bar_chart', shText: 'Minibar'},
  {text: 'Modem', faIcon: 'faRoute', shText: 'Modem'},
  {text: 'Modem jack', faIcon: 'faRoute', shText: 'Modem jack'},
  {text: 'Multi-line phone', faIcon: 'faChartLine', shText: 'Multi-line phone'},
  {text: 'Newspaper', faIcon: 'faPrint', shText: 'Newspaper'},
  {text: 'Non-smoking', matIcon: 'smoke_free', shText: 'Non-smoking'},
  {text: 'Notepads', matIcon: 'note_add', shText: 'Notepads'},
  {
    text: 'Office supplies',
    matIcon: 'local_post_office',
    shText: 'Office supplies',
  },
  {text: 'Oven', matIcon: 'confirmation_number', shText: 'Oven'},
  {
    text: 'Pay per view movies on TV',
    matIcon: 'local_movies',
    shText: 'Pay per view ',
  },
  {text: 'Pens', matIcon: 'open_with', shText: 'Pens'},
  {text: 'Phone in bathroom', faIcon: 'faBath', shText: 'bathroom Phone'},
  {text: 'Plates and bowls', faIcon: 'faBowlingBall', shText: 'Plates/bowls'},
  {text: 'Pots and pans', matIcon: 'gamepad', shText: 'Pots/pans'},
  {text: 'Prayer mats', matIcon: 'money', shText: 'Prayer mats'},
  {text: 'Printer', faIcon: 'faPrint', shText: 'Printer'},
  {text: 'Private bathroom', matIcon: 'lock', shText: 'Private bathroom'},
  {text: 'Queen bed', faIcon: 'faChessQueen', shText: 'Queen bed'},
  {text: 'Recliner', matIcon: 'event_seat', shText: 'Recliner'},
  {text: 'Refrigerator', matIcon: 'ballot', shText: 'Refrigerator'},
  {text: 'Refrigerator with ice maker', matIcon: 'ballot', shText: 'ice maker'},
  {
    text: 'Remote control television',
    matIcon: 'tv',
    shText: 'Remote control TV',
  },
  {text: 'Rollaway bed', faIcon: 'faBed', shText: 'Rollaway bed'},
  {text: 'Safe', matIcon: 'security', shText: 'Safe'},
  {text: 'Scanner', matIcon: 'scanner', shText: 'Scanner'},
  {
    text: 'Separate closet',
    matIcon: 'speaker_group',
    shText: 'Separate closet',
  },
  {
    text: 'Separate modem line available',
    faIcon: 'faRoute',
    shText: 'modem line',
  },
  {text: 'Shoe polisher', faIcon: 'faShoePrints', shText: 'Shoe polisher'},
  {text: 'Shower only', matIcon: 'hot_tub', shText: 'Shower only'},
  {
    text: 'Silverware/utensils',
    matIcon: 'details',
    shText: 'Silverware/utensils',
  },
  {text: 'Sitting area', faIcon: 'faChartArea', shText: 'Sitting area'},
  {
    text: 'Smoke detectors',
    matIcon: 'smoking_rooms',
    shText: 'Smoke detectors',
  },
  {text: 'Smoking', matIcon: 'smoking_rooms', shText: 'Smoking'},
  {text: 'Sofa bed', faIcon: 'faBed', shText: 'Sofa bed'},
  {text: 'Speaker phone', matIcon: 'speaker_phone', shText: 'Speaker phone'},
  {text: 'Stereo', matIcon: 'voicemail', shText: 'Stereo'},
  {text: 'Stove', matIcon: 'settings_overscan', shText: 'Stove'},
  {
    text: 'Tape recorder',
    matIcon: 'record_voice_over',
    shText: 'Tape recorder',
  },
  {text: 'Telephone', matIcon: 'phone', shText: 'Telephone'},
  {
    text: 'Telephone for hearing impaired',
    matIcon: 'phonelink_ring',
    shText: 'Telephone for HI',
  },
  {
    text: 'Telephones with message light',
    matIcon: 'contact_phone',
    shText: 'Telephones with ML',
  },
  {
    text: 'Toaster oven',
    matIcon: 'confirmation_number',
    shText: 'Toaster oven',
  },
  {text: 'Trouser/Pant press', matIcon: 'how_to_reg', shText: 'Trouser/Pant'},
  {
    text: 'Turn down service',
    matIcon: 'room_service',
    shText: 'Turn down service',
  },
  {text: 'Twin bed', faIcon: 'faBed', shText: 'Twin bed'},
  {text: 'Vaulted ceilings', matIcon: 'view_comfy', shText: 'Vaulted ceilings'},
  {text: 'VCR movies', matIcon: 'local_movies', shText: 'VCR movies'},
  {text: 'VCR player', matIcon: 'local_offer', shText: 'VCR player'},
  {text: 'Video games', matIcon: 'videocam', shText: 'Video games'},
  {text: 'Voice mail', matIcon: 'mail', shText: 'Voice mail'},
  {text: 'Wake-up calls', matIcon: 'access_time', shText: 'Wake-up calls'},
  {text: 'Water closet', matIcon: 'branding_watermark', shText: 'Water closet'},
  {
    text: 'Water purification system',
    matIcon: 'filter_b_and_w',
    shText: 'pure water',
  },
  {text: 'Wet bar', matIcon: 'filter_frames', shText: 'Wet bar'},
  {
    text: 'Wireless internet connection',
    matIcon: 'signal_cellular_4_bar',
    shText: 'WIFI',
  },
  {text: 'Wireless keyboard', matIcon: 'keyboard', shText: 'Wireless keyboard'},
  {
    text: 'Adaptor available for telephone PC use',
    matIcon: 'keyboard',
    shText: 'telephone PC Adaptor',
  },
  {
    text: 'Air conditioning individually controlled in room',
    matIcon: 'ac_unit',
    shText: "Room's AC",
  },
  {
    text: 'Bathtub & whirlpool separate',
    matIcon: 'hot_tub',
    shText: 'Bathtub/whirlpool',
  },
  {
    text: 'Telephone with data ports',
    matIcon: 'phone',
    shText: 'data ports telephone',
  },
  {text: 'CD player', matIcon: 'shutter_speed', shText: 'CD player'},
  {
    text: 'Complimentary local calls time limit',
    matIcon: 'leak_add',
    shText: "local calls's limit",
  },
  {
    text: 'Extra person charge for rollaway use',
    matIcon: 'strikethrough_s',
    shText: 'rollway charges',
  },
  {text: 'Down/feather pillows', faIcon: 'faBed', shText: 'pillows'},
  {
    text: 'Desk with electrical outlet',
    matIcon: 'show_chart',
    shText: 'electrical Desk',
  },
  {text: 'ESPN available', faIcon: 'faCoffee', shText: 'ESPN available'},
  {text: 'Foam pillows', faIcon: 'faBed', shText: 'Foam pillows'},
  {text: 'HBO available', faIcon: 'faSwatchbook', shText: 'HBO available'},
  {text: 'High ceilings', faIcon: 'faLightbulb', shText: 'High ceilings'},
  {text: 'Marble bathroom', faIcon: 'faBath', shText: 'Marble bathroom'},
  {
    text: 'List of movie channels available',
    matIcon: '',
    shText: 'movies channels',
  },
  {text: 'Pets allowed', matIcon: 'line_style', shText: 'Pets friendly'},
  {text: 'Oversized bathtub', matIcon: 'hot_tub', shText: 'Oversized bathtub'},
  {text: 'Shower', faIcon: 'faShower', shText: 'Shower'},
  {text: 'Sink in-room', faIcon: 'faSink', shText: "Room's Sink"},
  {
    text: 'Soundproofed room',
    faIcon: 'faSoundcloud',
    shText: 'Soundproofed room',
  },
  {text: 'Storage space', faIcon: 'faStoreAlt', shText: 'Storage space'},
  {text: 'Tables and chairs', faIcon: 'faTable', shText: 'Tables/chairs'},
  {text: 'Two-line phone', matIcon: 'dialer_sip', shText: 'Two-line phone'},
  {text: 'Walk-in closet', matIcon: 'alarm_on', shText: 'Walk-in closet'},
  {text: 'Washer/dryer', faIcon: 'faHandsWash', shText: 'Washer/dryer'},
  {text: 'Weight scale', faIcon: 'faWeight', shText: 'Weight scale'},
  {text: 'Welcome gift', faIcon: 'faBolt', shText: 'Welcome gift'},
  {
    text: 'Spare electrical outlet available at desk',
    faIcon: 'faTable',
    shText: 'electrical desk',
  },
  {
    text: 'Non-refundable charge for pets',
    faIcon: 'faDog',
    shText: 'Non-refundable pets',
  },
  {
    text: 'Refundable deposit for pets',
    faIcon: 'faDog',
    shText: 'Refundable pets',
  },
  {
    text: 'Separate tub and shower',
    matIcon: 'hot_tub',
    shText: 'seperate tub/shower',
  },
  {
    text: 'Entrance type to guest room',
    matIcon: 'meeting_room',
    shText: 'Entrance guestroom',
  },
  {text: 'Ceiling fan', faIcon: 'faFan', shText: 'Ceiling fan'},
  {text: 'CNN available', matIcon: 'tv', shText: 'CNN available'},
  {
    text: 'Electrical adaptors available',
    faIcon: 'faPlug',
    shText: 'Electrical adaptors',
  },
  {text: 'Buffet breakfast', faIcon: 'faBuffer', shText: 'Buffet breakfast'},
  {text: 'Accessible room', matIcon: 'meeting_room', shText: 'Accessible room'},
  {text: 'Closets in room', matIcon: 'meeting_room', shText: 'Closets in room'},
  {text: 'DVD player', matIcon: 'movie_filter', shText: 'DVD player'},
  {text: 'Mini-refrigerator', matIcon: 'ballot', shText: 'Mini-refrigerator'},
  {
    text: 'Separate line billing for multi-line phone',
    matIcon: 'dialer_sip',
    shText: 'multi-line billing',
  },
  {
    text: 'Self-controlled heating/cooling system',
    matIcon: '',
    shText: 'heating/cooling system',
  },
  {text: 'Toaster', matIcon: '', shText: 'Toaster'},
  {
    text: 'Analog data port',
    matIcon: 'perm_data_setting',
    shText: 'Analog data port',
  },
  {text: 'Collect calls', matIcon: 'leak_add', shText: 'Collect calls'},
  {
    text: 'International calls',
    matIcon: 'local_phone',
    shText: 'International calls',
  },
  {text: 'Carrier access', matIcon: '', shText: 'Carrier access'},
  {
    text: 'Interstate calls',
    matIcon: 'local_phone',
    shText: 'Interstate calls',
  },
  {
    text: 'Intrastate calls',
    matIcon: 'local_phone',
    shText: 'Interstate calls',
  },
  {text: 'Local calls', matIcon: 'phone_callback', shText: 'Local calls'},
  {
    text: 'Long distance calls',
    matIcon: 'local_phone',
    shText: 'calls distance',
  },
  {
    text: 'Operator-assisted calls',
    matIcon: 'phone_paused',
    shText: 'OP-assisted calls',
  },
  {
    text: 'Credit card access calls',
    matIcon: 'phone_in_talk',
    shText: 'calling creditCards',
  },
  {
    text: 'Calling card calls',
    matIcon: 'contact_phone',
    shText: 'Calling card calls',
  },
  {text: 'Toll free calls', matIcon: 'contact_mail', shText: 'Toll calls'},
  {
    text: 'Universal AC/DC adaptors',
    matIcon: 'ac_unit',
    shText: 'AC/DC adaptors',
  },
  {text: 'Bathtub seat', faIcon: 'faToiletPaper', shText: 'Bathtub seat'},
  {text: 'Canopy/poster bed', faIcon: 'faBed', shText: 'Canopy/poster'},
  {text: 'Cups/glassware', matIcon: 'money', shText: 'Cups/glassware'},
  {
    text: 'Entertainment center',
    matIcon: 'movie',
    shText: 'Entertainment center',
  },
  {
    text: 'Family/oversized room',
    matIcon: 'meeting_room',
    shText: 'Family room',
  },
  {
    text: 'Hypoallergenic bed',
    matIcon: 'kitchen',
    shText: 'Hypoallergenic bed',
  },
  {
    text: 'Hypoallergenic pillows',
    matIcon: 'event_seat',
    shText: 'Hypoallergenic pillows',
  },
  {text: 'Lamp', matIcon: 'highlight', shText: 'Lamp'},
  {
    text: 'Meal included - breakfast',
    matIcon: 'room_service',
    shText: 'Meal / breakfast',
  },
  {
    text: 'Meal included - continental breakfast',
    matIcon: 'room_service',
    shText: 'continental breakfast',
  },
  {
    text: 'Meal included - dinner',
    matIcon: 'location_city',
    shText: 'Meal / dinner',
  },
  {
    text: 'Meal included - lunch',
    matIcon: 'room_service',
    shText: 'Meal / lunch',
  },
  {text: 'Shared bathroom', matIcon: 'kitchen', shText: 'Shared bathroom'},
  {
    text: 'Telephone TDD/Textphone',
    matIcon: 'speaker_phone',
    shText: 'TDD/Textphone',
  },
  {text: 'Water bed', faIcon: 'faBed', shText: 'Water bed'},
  {text: 'Extra adult charge', matIcon: 'attach_money', shText: 'adult charge'},
  {text: 'Extra child charge', matIcon: 'attach_money', shText: 'child charge'},
  {
    text: 'Extra child charge for rollaway use',
    matIcon: 'bar_chart',
    shText: 'charge for rollaway',
  },
  {
    text: 'Meal included:  full American breakfast',
    matIcon: 'room_service',
    shText: 'Meal/US breakfast',
  },
  {text: 'Futon', matIcon: 'border_outer', shText: 'Futon'},
  {text: 'Murphy bed', faIcon: 'faBed', shText: 'Murphy bed'},
  {
    text: 'Tatami mats',
    matIcon: 'format_indent_increase',
    shText: 'Tatami mats',
  },
  {text: 'Single bed', matIcon: 'airline_seat_flat', shText: 'Single bed'},
  {text: 'Annex room', matIcon: 'meeting_room', shText: 'Annex room'},
  {text: 'Free newspaper', faIcon: 'faPrint', shText: 'Free newspaper'},
  {
    text: 'Honeymoon suites',
    matIcon: 'insert_invitation',
    shText: 'Honeymoon suites',
  },
  {
    text: 'Complimentary high speed internet in room',
    faIcon: 'faWifi',
    shText: 'high speed internet',
  },
  {
    text: 'Maid service',
    matIcon: 'store_mall_directory',
    shText: 'Maid service',
  },
  {
    text: 'PC hook-up in room',
    matIcon: 'store_mall_directory',
    shText: 'PC hook-up',
  },
  {text: 'Satellite television', matIcon: 'satellite', shText: 'Satellite TV'},
  {text: 'VIP rooms', matIcon: 'satellite', shText: 'VIP rooms'},
  {
    text: 'Cell phone recharger',
    matIcon: 'contact_phone',
    shText: 'phone recharger',
  },
  {text: 'DVR player', matIcon: 'movie_filter', shText: 'DVR player'},
  {text: 'iPod docking station', faIcon: 'faMicrophone', shText: 'iPod docking'},
  {text: 'Media center', matIcon: 'perm_media', shText: 'Media center'},
  {
    text: 'Plug & play panel',
    matIcon: 'play_for_work',
    shText: 'Plug/play panel',
  },
  {text: 'Satellite radio', matIcon: 'satellite', shText: 'Satellite radio'},
  {text: 'Video on demand', matIcon: 'movie_filter', shText: 'Video on demand'},
  {
    text: 'Exterior corridors',
    matIcon: 'view_carousel',
    shText: 'Exterior corridors',
  },
  {text: 'Gulf view', matIcon: 'play_for_work', shText: 'Gulf view'},
  {
    text: 'Accessible room',
    matIcon: 'store_mall_directory',
    shText: 'Accessible room',
  },
  {
    text: 'Interior corridors',
    matIcon: 'view_carousel',
    shText: 'Interior corridors',
  },
  {text: 'Mountain view', matIcon: 'view_carousel', shText: 'Mountain view'},
  {text: 'Ocean view', matIcon: 'insert_chart', shText: 'Ocean view'},
  {
    text: 'High speed internet access fee',
    faIcon: 'faWifi',
    shText: 'internet fee',
  },
  {text: 'High speed wireless', faIcon: 'faWifi', shText: 'High speed WIFI'},
  {
    text: 'Premium movie channels',
    matIcon: 'view_comfy',
    shText: 'Premium movies',
  },
  {text: 'Slippers', matIcon: 'camera_rear', shText: 'Slippers'},
  {text: 'First nighters kit', matIcon: 'flare', shText: 'nighters kit'},
  {
    text: 'Chair provided with desk',
    faIcon: 'faWheelchair',
    shText: 'desk chair',
  },
  {text: 'Pillow top mattress', faIcon: 'faBed', shText: 'Pillow mattress'},
  {text: 'Feather bed', faIcon: 'faBed', shText: 'Feather bed'},
  {text: 'Duvet', faIcon: 'faBed', shText: 'Duvet'},
  {
    text: 'Luxury linen type',
    matIcon: 'edit_attributes',
    shText: 'Luxury linen',
  },
  {
    text: 'International channels',
    matIcon: 'view_comfy',
    shText: 'International channels',
  },
  {text: 'Pantry', matIcon: 'tonality', shText: 'Pantry'},
  {text: 'Dish-cleaning supplies', faIcon: 'faSoap', shText: 'Dish-cleaning '},
  {text: 'Double vanity', faIcon: 'faMarsDouble', shText: 'Double vanity'},
  {
    text: 'Lighted makeup mirror',
    matIcon: 'settings_overscan',
    shText: 'makeup mirror',
  },
  {
    text: 'Upgraded bathroom amenities',
    faIcon: 'faBath',
    shText: 'bathroom amenities',
  },
  {
    text: 'VCR player available at front desk',
    matIcon: 'movie_filter',
    shText: 'VCR player desk',
  },
  {text: 'Instant hot water', faIcon: 'faHotTub', shText: 'Instant hot water'},
  {text: 'Outdoor space', faIcon: 'faDungeon', shText: 'Outdoor space'},
  {text: 'Hinoki tub', matIcon: 'hot_tub', shText: 'Hinoki tub'},
  {text: 'Private pool', faIcon: 'faSwimmingPool', shText: 'Private pool'},
  {
    text: 'High Definition (HD) Flat Panel Television  - 32 inches or greater ',
    matIcon: 'tv',
    shText: 'Large HDTV',
  },
  {
    text: 'Room windows open',
    faIcon: 'faWindowClose',
    shText: 'Room windows open',
  },
  {
    text: 'Bedding type unknown or unspecified',
    matIcon: 'grain',
    shText: 'Bedding unspecified type',
  },
  {text: 'Full bed', faIcon: 'faBed', shText: 'Full bed'},
  {text: 'Round bed', faIcon: 'faBed', shText: 'Round bed'},
  {text: 'TV', matIcon: 'tv', shText: 'TV'},
  {text: 'Child rollaway', faIcon: 'faChild', shText: 'Child rollaway'},
  {
    text: 'DVD player available at front desk',
    matIcon: 'movie_filter',
    shText: 'DVD player desk',
  },
  {
    text: 'Video game player',
    matIcon: 'settings_input_svideo',
    shText: 'Video player',
  },
  {
    text: 'Video game player available at front desk',
    matIcon: 'settings_input_svideo',
    shText: 'Desk Video player',
  },
  {text: 'Dining room seats', faIcon: 'faChair', shText: 'Dining seats'},
  {text: 'Full size mirror', matIcon: 'settings_overscan', shText: 'Mirror'},
  {
    text: 'Mobile/cellular phones',
    matIcon: 'contacts',
    shText: 'Mobile phones',
  },
  {text: 'Movies', matIcon: 'movie', shText: 'Movies'},
  {
    text: 'Multiple closets',
    matIcon: 'playlist_play',
    shText: 'Multiple closets',
  },
  {text: 'Plates/glassware', matIcon: 'select_all', shText: 'Plates/glassware'},
  {
    text: 'Safe large enough to accommodate a laptop',
    matIcon: 'laptop_chromebook',
    shText: 'laptop place',
  },
  {
    text: 'Bed linen thread count',
    matIcon: 'filter_9_plus',
    shText: 'Bed thread count',
  },
  {text: 'Blackout curtain', matIcon: 'flip', shText: 'Blackout curtain'},
  {
    text: 'Bluray player',
    matIcon: 'settings_input_svideo',
    shText: 'Bluray player',
  },
  {text: 'Device with mp3', matIcon: 'important_devices', shText: 'mp3 Device'},
  {
    text: 'No adult channels or adult channel lock',
    matIcon: 'view_comfy',
    shText: 'No adult channel',
  },
  {
    text: 'Non-allergenic room',
    matIcon: 'filter_b_and_w',
    shText: 'Non-allergenic',
  },
  {text: 'Pillow type', faIcon: 'faBed', shText: 'Pillow type'},
  {
    text: 'Seating area with sofa/chair',
    faIcon: 'faChair',
    shText: 'sofa/chair seats',
  },
  {text: 'Separate toilet area', faIcon: 'faToilet', shText: 'toilet area'},
  {text: 'Web enabled', matIcon: 'settings_voice', shText: 'Web enabled'},
  {text: 'Widescreen TV', matIcon: 'tv', shText: 'Widescreen TV'},
  {
    text: 'Other data connection',
    matIcon: 'timeline',
    shText: 'Other connection',
  },
  {
    text: 'Phoneline billed separately',
    matIcon: 'announcement',
    shText: 'Phoneline billed',
  },
  {
    text: 'Separate tub or shower',
    matIcon: 'hot_tub',
    shText: 'seperate tub/shower',
  },
  {text: 'Video games', matIcon: 'missed_video_call', shText: 'Video games'},
  {text: 'Roof ventilator', faIcon: 'faBuilding', shText: 'Roof ventilator'},
  {text: "Children's playpen", faIcon: 'faChild', shText: "Children's playpen"},
  {text: 'Plunge pool', matIcon: 'select_all', shText: 'Plunge pool'},
  {text: 'DVD movies', matIcon: 'music_video', shText: 'DVD movies'},
  {text: 'Air filtration', matIcon: 'call_split', shText: 'Air filtration'},
  {
    text: 'Exercise Equipment in Room',
    matIcon: 'toc',
    shText: 'Equipment Exercise',
  },
  {
    text: 'Wrapped coffee and condiments packages',
    matIcon: 'subject',
    shText: 'coffee/condiments packages',
  },
  {
    text: 'TV remotes disinfected',
    matIcon: 'domain_disabled',
    shText: 'TV remotes',
  },
  {
    text: 'Extraneous room amenities removed',
    matIcon: 'business_center',
    shText: 'amenities removed',
  },
  {
    text: 'Electronics controlled by personal mobile device',
    matIcon: 'network_check',
    shText: 'electronics controll-mobile',
  },
  {
    text: 'TV controlled by personal mobile device ',
    matIcon: 'live_tv',
    shText: 'TV controll-mobile ',
  },
  {
    text: 'Voice enabled room controls ',
    matIcon: 'settings_voice',
    shText: 'room voice enable',
  },
  {
    text: 'Room air purification system',
    matIcon: 'filter_b_and_w',
    shText: 'air purification',
  },
  {text: 'Allergy friendly room', matIcon: 'spa', shText: 'Allergy friendly'},
  {
    text: 'Medical grade air purification system',
    matIcon: 'filter_b_and_w',
    shText: 'Medical grade',
  },
  {
    text: 'All surfaces sanitized between stays',
    faIcon: 'faBed',
    shText: 'surfaces sanitized',
  },
  {
    text: 'TV has connection for external devices',
    matIcon: 'important_devices',
    shText: "TV connection's devices",
  },
  {
    text: 'Streaming services supported',
    matIcon: 'view_stream',
    shText: 'Streaming services',
  },
  {
    text: 'In room workout program',
    matIcon: 'network_check',
    shText: 'room workout',
  },
];
